### ISSUE TITLE
Hit Dice are not being included when extending a monster

### ISSUE THREAD

**Issue by nrabins** [javalent/fantasy-statblocks#190]
I'm using YAML Frontmatter to define a monster like so:
```
---
statblock: true
name: Yamlsaur
extends: Ancient Black Dragon
image: "[[Pasted image 20230401082722.png]]"
---
```
After adding it to the Bestiary via the "Parse Frontmatter for Creatures" command and starting a combat with it and the monster it extends, the original monster (Ancient Black Dragon) has rolled HP, while the custom monster (Yamlsaur) does not.

Original Monster (Ancient Black Dragon):
![image](https://user-images.githubusercontent.com/1879640/233795431-13e50006-1869-419a-912e-a126381b4509.png)

Custom Monster (Yamlsaur):
![image](https://user-images.githubusercontent.com/1879640/233795581-79591a72-a1b2-4808-91d3-cc3cc97ff1a9.png)

Versions:
- Fantasy Statblocks: 3.5.4
- Initiative Tracker: 9.6.4
- 
Please let me know if I can provide more information or if I've misconfigured something. Thanks!

**Comment by sigrunixia** [comment]
Pinning

**Comment by valentine195** [comment]
I think this is actually an issue with Initiative Tracker

**Comment by valentine195** [comment]
This is fixed in Initiative Tracker v12
