### ISSUE TITLE
Monster isn't being inherited when using the "monster" field in YAML Frontmatter

### ISSUE THREAD

**Issue by nrabins** [javalent/fantasy-statblocks#191]
I'm using YAML Frontmatter to define a monster like so:
```
---
statblock: true
name: Yamlsaur
monster: Ancient Black Dragon
image: "[[Pasted image 20230401082722.png]]"
---
```

After adding it to the Bestiary via the "Parse Frontmatter for Creatures" command and starting a combat with it and the monster it extends, the original monster (Ancient Black Dragon) has its full stats, while the custom monster (Yamlsaur) does not.

Original Monster (Ancient Black Dragon):
![image](https://user-images.githubusercontent.com/1879640/233795979-67afec6b-6136-4765-b25c-23b4cb11896f.png)

Custom Monster (Yamlsaur):
![image](https://user-images.githubusercontent.com/1879640/233796005-0d0cddcf-64b8-4bf2-90e6-89348764a3ac.png)

Versions:
- Fantasy Statblocks: 3.5.4
- Initiative Tracker: 9.6.4

Please let me know if I can provide more information or if I've misconfigured something. Thanks!

**Comment by sigrunixia** [comment]
Tied to issue #190.
