### ISSUE TITLE
[Code]: Statblocks Internal CSS Update

### ISSUE THREAD

**Issue by sigrunixia** [javalent/fantasy-statblocks#200]
# Summary
I am requesting to submit an update (It may take a day or two as I also need to submit an updated PF2E layout at the same time) to the selectors assigned within the svelte files of Fantasy Statblocks. 

## Description
I'll make some separate comments about this as I'll post exactly what changes I would do. In brief, I would make some selector names more specific to what file they are currently housed in, which by effect also makes it more relevant to what function they pertain to.

## Motivation and Context
In making a Bootstrap, as well as spending some "recharge" time going back and updating one of my beloved statblocks, I find myself annoyed yet again how different div classes have children that have the same children name. Unless I am on a second monitor, and am looking at the Obsidian Devtools or the src for the repo the entire time, I find myself getting mixed up on what exactly I should be editing when it comes to some selectors. Ideally, I should be focused solely on spending time in the IDE, and Obsidian, making pretty statblocks. 

## How Has This Been Tested?
Testing _shouldn't_ be needed as it's a rename. o.o 

## Types of changes

- [X] Breaking change (fix or feature that would cause existing functionality to change)

- Breaking because application right now would break a layout design.

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation. (Which I shall take care of too!)

**Comment by sigrunixia** [comment]
Figure I'd do commits on my own fork for line numbers...

## Traits.Svelt
https://github.com/sigrunixia/fantasy-statblocks/commit/7d55774ed2eadcece111678dfd124fd59a488c65

Specifically renaming instances of property to trait to better reflect that this controls traits block styling.

**Comment by sigrunixia** [comment]
## Property Line
Similar treatment except this one gets to keep property wording because.. its a property block
https://github.com/sigrunixia/fantasy-statblocks/commit/25f2489ee9b9aa56f508b9f20db618e6b4e22849


## Dice Holder
Same Treatment, but a question below.

https://github.com/sigrunixia/fantasy-statblocks/blob/Code-Svelte-Fluffy/src/view/ui/DiceHolder.svelte

```svelte
<style>
    .dice-text {
        display: inline;
        white-space: pre-line;
        text-indent: 0;
    }
    .dice-text {
        display: inline;
        margin: 0;
    }
</style>
```

Why is this one repeated twice?

**Comment by sigrunixia** [comment]
## Text.svelte
```svelte
    <div class="line">
        <TextContentHolder render={item.markdown} {property} />
    </div>
```

Lines 26-28. If this div class is exclusive to text/the text block, we should rename it. I want to confirm first though. 

Textcontent.svelte can remain as is as long as it's the only one with .inline verbiage.

**Comment by sigrunixia** [comment]
Picking your brain a moment on more css. Headers in statblocks. We currently apply header classes to them. How hard for us would it be to make it be statblock specific on those? (Ran into a theme issue last night while working on one of my statblocks and and not exactly pleased about it...). 

The goal would be ultimately to make it so someone has to specifically stylize statblocks with CSS by targeting selectors within Statblocks. That accidential theme crossovers cant happen.

**Comment by valentine195** [comment]
Well, I made them actual header elements (h1, h2 etc) to make it natively adjust size. Unfortunately this means generic theme selectors will apply to them.

I could go back to styled divs and manually apply the header sizes. It's easy enough.

**Comment by sigrunixia** [comment]
> I could go back to styled divs and manually apply the header sizes. It's easy enough.

Thinking out loud. A plugin, especially one where individuals like to style it such as Statblocks and to an extent Admonitions, needs to be able to stand on its own. It's an additive to Obsidian, and can take from Obsidian, but Obsidian shouldn't be able to apply more than its requirements for a plugin, and what you as a developer additionally allow on it. 

If that were so, then it would be more feasible and realistic to approach themes who do "encroach" so to speak and create a standard ourselves that says "Hey, you hate how X statblock looks on your create theme? Style it with these layout selectors please, and make it toggleble with style settings. Here's how to do it."

**Comment by sigrunixia** [comment]
Some questions before I PR This:

```ts
    import type { Trait } from "types";
```

Types is not resolving. Is this still a valid call? If not, what does it need to be updated to?
