### ISSUE TITLE
[Bug]: Wrong Css Padding/Margin on note preview

### ISSUE THREAD

**Issue by Yilmas** [javalent/fantasy-statblocks#203]
## Version Check
Pssst, the most current version is 1.1.16, and not 1.1.9
![image](https://user-images.githubusercontent.com/6323003/235012476-3fec52a7-9ab4-4c9b-9155-8f4c54ab6885.png)

## What is the current behavior?
When I hover over a link to a note that only contains a statblock, it creates this preview where the note has received some padding/margin of sorts. I assume it is the same css that normally centers the statblock in a note, whereas in a preview it shouldn't (in my opinion). Since it pushes everything around, including if that statblock preview has a link to another statblock - it will then open a preview that expands outside the Obsidian window.

For verification purposes, tested on default theme as well.

## Screenshots and Video
Image below shows the issue.
![image](https://user-images.githubusercontent.com/6323003/235012127-b9511a10-40dd-4ec2-bc2a-3853b41d0c65.png)

Image below shows how the issue can become worse when you have nested statblocks through wikilinks.
![image](https://user-images.githubusercontent.com/6323003/235012172-d24a9364-9673-4cbd-be00-7eee7ebed956.png)

**Comment by sigrunixia** [comment]
I think this may be the reappearing popovers in Pf2e. Attempting update.

**Comment by sigrunixia** [comment]
This was resolved with release #205.
