### ISSUE TITLE
[Bug]: plugin stylesheet makes all links italic in reading mode

### ISSUE THREAD

**Issue by bszonye** [javalent/fantasy-statblocks#210]
## Version Check

3.6.0

## What is the expected behavior?

The plugin should not affect the formatting of text outside of statblocks.

## What is the current behavior?

With the plugin enabled, all links become italicized in reading mode.

## What are the A-to-Z Steps to Reproduce your Bug?

1. Create a new vault.
2. Install and enable the plugin.
3. Create a note.
4. Add a link to the note. (Wiki & Markdown style links are both affected.)
5. Switch to reading mode.

## Error Codes
No error codes.

The problem appears to be caused by this recent addition to the stylesheet:
https://github.com/javalent/fantasy-statblocks/blob/fbb2d86d5120b06996c9d6edc5fc16f447d39fb5/src/view/Statblock.svelte#L205-L207

## Screenshots and Video

Edit mode:
![image](https://user-images.githubusercontent.com/5016349/235376727-797cfccc-8934-4519-8c48-8951db4ea8aa.png)
Read mode:
![image](https://user-images.githubusercontent.com/5016349/235376748-c2e8e172-2299-4c9d-93a1-67608cef5761.png)

**Comment by sigrunixia** [comment]
This should be fixed. :)

**Comment by bszonye** [comment]
Verified. Thanks for the quick fix!
