### ISSUE TITLE
[Bug]: Exporting Layouts on Android is not working

### ISSUE THREAD

**Issue by sigrunixia** [javalent/fantasy-statblocks#216]
The bug tracker is **ONLY** used for reporting bugs.

## Version Check

Obsidian Android, Latest Version. s23 ultra.

User `Mako 🦈🦈🦈#8888`

Android devices seems unable to export layouts.

## What is the expected behavior?

It is expected that when exporting a layout happens, it would prompt the user the opportunity to save the file elsewhere.

## What is the current behavior?

Either the Obsidian application is unresponsive, stalls, or crashes.

## What are the A-to-Z Steps to Reproduce your Bug?

1. Go to Statblock Settings
2. Go to Layout section
3. Try to export layout
4. No Profit. :(

## Error Codes

Unable to collect this info. This is similar to https://github.com/javalent/admonitions/issues/237.

## Screenshots and Video

None given.

**Comment by Pyrix371** [comment]
I can confirm this same issue. Built a layout on my phone, tried to export it and use the file to import to my pc, but there is no layout file. On my instance, tapping the export button has zero effect at all.
