### ISSUE TITLE
Actions of base monster not being overwritten

### ISSUE THREAD

**Issue by Darthfett** [javalent/fantasy-statblocks#222]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/fantasy-statblocks/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc) and found no similar reports.

### Expected Behavior

When I define a custom Gorgon with custom actions using the `actions` section, I should see that the actions are replaced, with all other stats coming from the base monster.

### Current behaviour

I am instead seeing that the actions are being added to.

### Reproduction

```statblock
monster: Gorgon
name: "Gorgon (Boss)"
hp: 168
actions:
  - name: "Gore"
    desc: "Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 16 (2d10 + 5) piercing damage."
    attack_bonus: 8
    damage_dice: "2d10"
    damage_bonus: 5
  - name: "Hooves"
    desc: "Melee Weapon Attack: +8 to hit, reach 5 ft., one target. Hit: 14 (2d8 + 5) bludgeoning damage."
    attack_bonus: 8
    damage_dice: "2d8"
    damage_bonus: 5
  - name: "Petrifying Breath (Recharge 5-6)"
    desc: "The gorgon exhales petrifying gas in a 30-foot cone. Each creature in that area must succeed on a DC 13..."
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.2.8

### Fantasy Statblocks Version

3.6.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by sigrunixia** [comment]
This should be fixed now. Can you retry with the updated version and double check?

**Comment by Darthfett** [comment]
Thanks!  Sorry, I didn't realize I wasn't fully updated, and just now figured out how to update plugins.  I'm seeing that the actions side of things is fixed, but it looks like the traits side is having a similar issue.  I opened it as a separate ticket, seeing as this one is closed, and not quite the same issue.

https://github.com/javalent/fantasy-statblocks/issues/224

**Comment by Darthfett** [comment]
Just noticed that this fix was put in super quick, and was not an already fixed issue like I already thought.  Wanted to say thank you for the quick turn-around!!
