### ISSUE TITLE
QoL Feature: Layout Editor Suggester

### ISSUE THREAD

**Issue by sigrunixia** [javalent/fantasy-statblocks#226]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous [Statblocks Discussions](https://github.com/javalent/fantasy-statblocks/discussions) and didn't find any similar feature requests.
- [X] I searched previous [Issues](https://github.com/javalent/fantasy-statblocks/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and didn't find any similar feature requests.

### Feature description

Editor suggester for layouts in Statblocks

### Solution

Once a layout is specified, editor suggester for the different keys you have registered in the layout.

### Alternatives

Currently None

### Additional Information

This is very preliminary

**Comment by valentine195** [comment]
This was only partially implemented.

**Comment by valentine195** [comment]
Implemented in #257
