### ISSUE TITLE
[Bug]: Transparent table block

### ISSUE THREAD

**Issue by pamput** [javalent/fantasy-statblocks#230]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/fantasy-statblocks/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc) and found no similar reports.

### Expected Behavior

Table blocks should be readable when using a dark theme in obsidian.

### Current behaviour

In its current implementation tables are rendered with a transparent background in some themes like Dracula Official. This isn't a problem if the global theme is light, but if a dark one is used this makes the data inside to be not readable:

![image](https://github.com/javalent/fantasy-statblocks/assets/3295190/85cf9bee-2f6f-4efa-98e7-86fbc3e7ef95)

Allegedly this might be an issue caused by a bad implementation of the theme itself.

### Reproduction

Use Dracula official in dark mode theme.

![image](https://github.com/javalent/fantasy-statblocks/assets/3295190/930526cf-a38a-4fe4-a9ba-05300497e9aa)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [X] macOS
- [X] Windows

### Obsidian Version Check

1.3.4

### Plugin Version

3.6.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

At the moment it's easily to work around this by applying a custom snippet like this:

```css
.statblock.basic-pathfinder-2e-layout .table {
    background-color: var(--statblock-background-color) !important
}
```

![image](https://github.com/javalent/fantasy-statblocks/assets/3295190/ec1b31e4-50d9-434c-ac65-0973cd39deb9)

Obviously the above is a very dirty solution and potentially can cause issues. A real solution would be to add a class to the table based on the property displayed and making tables opaque by default.

This is experienced using the PF2 theme.

**Comment by sigrunixia** [comment]
Changing the class names of the CSS within the Statblocks is a project I am actively working on currently, specifically to address the issue of themes having an affect on statblocks when they shouldn't. 

So this is coming soon. :)
