### ISSUE TITLE
[Bug]: Bestiary isn't being synched with Obsidian Sync

### ISSUE THREAD

**Issue by daren-thomas** [javalent/fantasy-statblocks#232]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/fantasy-statblocks/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc) and found no similar reports.

### Expected Behavior

Statblocks that refer to monsters I've added on one Computer to a vault synchronized with Obsidian Sync _should_ show up on other computers (e.g. my tablet or another laptop).

### Current behaviour

Other computers do not know about these monsters.

### Reproduction

1. (precondition) Vault is synced with Obsidian Sync
2. Add a monster e.g. by exporting it from 5e.tools and then importing it to the bestiary in Settings
3. Create a note referencing the monster (see below)
5. Open note on another computer (e.g. another laptop or a tablet / mobile phone)

Example note reference:

```statblock
monster: Fox
name: Ember the Red Fox
```

### Which Operating Systems are you using?

- [ ] Android
- [X] iPhone/iPad
- [X] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

3.6.5

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

(workaround: export to png and use that in notes instead of the actual statblock. obviously, that's sub-optimal)

**Comment by valentine195** [comment]
Do these creatures show up if you restart Obsidian after your Sync finishes?

**Comment by daren-thomas** [comment]
No, I'm afraid they don't...

**Comment by sigrunixia** [comment]
Judging by the #Obsidian-Sync channel on the Obsidian Discord, there may be some tomfoolery happening. Let's try to rule out Sync itself as the issue.

## Info I Need

Can you first ensure this is enabled on every device?

<img width="935" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/68425372/8c3aefb7-3395-4366-9295-53fe2f6c79ba">

Then, do the following:
- Add entity to Bestiary on 1st device. 
- Check Sync Activity to ensure that the following updates. There may be multiple entries.

<img width="774" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/68425372/f62ee839-c37d-4520-82d4-32bd0afe759d">

Can you paste the part and timestamp of this log, then close Obsidian on device 1. (_This is for preservation purposes and to rule out the other devices being the "latest file"_)

Open Device 2, let it update, and check the Sync Log again to see what updates. Can you paste this log?

Open Device 3, let it update, and check the Sync Log again to see what updates. Can you paste this log?

**Comment by daren-thomas** [comment]
OK. Now I feel _really_ stupid. I'm sorry for bothering you: I hadn't even _seen_ any of those settings and jumped to conclusions. I'll try out your steps later today, but I'm pretty sure that this will solve the issue.

**Comment by sigrunixia** [comment]
> OK. Now I feel _really_ stupid. I'm sorry for bothering you: I hadn't even _seen_ any of those settings and jumped to conclusions. I'll try out your steps later today, but I'm pretty sure that this will solve the issue.

Don't feel stupid, because it's not the most apparent (or documented), and if done in the wrong order, can overwrite your bestiary settings. :)

**Comment by daren-thomas** [comment]
Tested. This works as advertised. TIL.
