### ISSUE TITLE
[Bug]: Embedded Notes not working in Statblock

### ISSUE THREAD

**Issue by MNielson** [javalent/fantasy-statblocks#241]
### Check for existing bug reports before submitting.

- [X] I searched for existing [Bug Reports](https://github.com/javalent/fantasy-statblocks/issues?q=is%3Aopen+label%3Abug+sort%3Aupdated-desc) and found no similar reports.

### Expected Behavior

I have a simple callback that takes a property as an array and creates a (markdown) string from it.
This string is a series of ![[X]]. So each element in the array should be interpreted as an embedded note.

The expected result would be ![[X]] (continuing for all other elements of the array) being Rendered as Markdown.

### Current behaviour

X is rendered instead, despite the Markdown being produced correctly.

Render as Markdown turned off to check output:
![image](https://github.com/javalent/fantasy-statblocks/assets/23503856/796f1c85-4f0d-448b-99d9-b5cb3a18aab7)

Render as Markdown turned on:
![image](https://github.com/javalent/fantasy-statblocks/assets/23503856/cde7da5c-47fe-4daa-b01b-64ed9c274e7b)
Only the array elements are rendered, not the array elements as embedded notes.
![image](https://github.com/javalent/fantasy-statblocks/assets/23503856/e4b73951-81cf-41bd-8c17-a75ba0802b5a)

### Reproduction

1. Launch Sandbox Vault and install Fantasy Statblocks
2. Create a new Layout "Testlayout" consisting of at least on Property Line Element
3. Link Monster Property = foo
4. Add the following code as a callback:

```
let output = "";

if ("foo" in monster) {
  let foo = monster.foo;
  for ( let x = 0; x < foo.length; x++){
    let bar = foo[x];
    output += "![[" + bar + "]] ";
  }
  return output;
}

```
5. Turn "Render as Markdown" on
6. Display Text = Test:
7. Set Testlayout as Default Layout
8. Create new Note "Dummy" with content "Dummycontent"
9. Create new Note Teststatblock with content:
```
```statblock
foo: 
  - Dummy

```
10. Don't forget to close your statblock (I just can't figure out how to get github to display the triple backtick at the end.
11. Switch to Read Mode
12. Result: 
![image](https://github.com/javalent/fantasy-statblocks/assets/23503856/07b9e7ca-af9d-4530-803b-a623ec670545)
Expected Result:
"Dummy:
Dummycontent" instead of "Dummy"

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

3.5.7

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Hey, unfortunately Obsidian's API for markdown rendering is really weird with embeds. Getting them to work is non-trivial and breaks other things. This is compounded by the link-replacing I do to get around the "links-in-yaml" issue.
