### ISSUE TITLE
🐞 Hitdice rendering issue

### ISSUE THREAD

**Issue by ElifCase** [javalent/fantasy-statblocks#254]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When rendering a statblock, the hitdice of the creature should be displayed after its hitpoints.

### Current behaviour

In read-mode, the statblock does not feature any hitdice. Using the console, no errors are displayed when opening or rendering the statblocked note.

### Reproduction

Using the basic 5e layout and an example statblock:

```statblock
name: Paladin (Tier 1)
size: Medium
type: humanoid
subtype: (any race)
alignment: depends on Party
ac: 16
hp: 34
hit_dice: 4d10+12
speed: 30ft
stats: [16, 8, 16, 10, 13, 14]
saves:
  - WIS: +3
  - CHA: +4
skillsaves:
  - Athletics: +5
senses: Passive Perception 11
languages: Celestial, Common
cr: 2
spells:
  - "The Paladin´s spellcasting ability is Charisma (spell save DC 12, +4 to hit with spell attacks). The paladin can cast the following spells:" 
  - 1/day: bless, command, shield of faith
traits:
  - name: Dueling
    desc: "When the paladin is wielding a melee weapon in one hand and no ther weapons, they gain a +2 bonus to damage rolls with that weapon (included in the longsword attack)"
actions:
  - name: Longsword
    desc: "Mellee Weapon Attack: +5 to hit, reach 5ft., one creature. Hit: 9 (1d8+5) slashing damage"
```

Using the File -> Open Sandbox Vault option, downloading & enabling Fantasy Stablocks and pasting the above statblock yields the same results

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.3.7 and 1.3.5

### Plugin Version

3.8.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Hi, the latest release should fix this.
