### ISSUE TITLE
QoL Feature: Search function & persistance with Combatant view

### ISSUE THREAD

**Issue by source-toad** [javalent/fantasy-statblocks#256]
### Please make sure this feature request hasn't been suggested before.

- [X] I searched previous Issues and didn't find any similar feature requests.

### Feature description

The combatant view is very convenient for monster statblock referencing, I would like some sort of search function enabling quick reference of statblocks without having to pull the statblock into a note.

### Solution

1. Persistence of the view. Unsure what current expected functionality is, but I find the view often dissappears when unused for a period. 
2. Search bar at top of view including suggester for quick searching and referencing of statblocks.
3. (Non-essential bonus only) Non-persistent editing of current statblock in the view. Having built in statblock layout functionality that changes portions of the statblock according to different values (e.g. qty of minions), it would be great to be able to chuck in values to be presented in the window.

### Alternatives

None at this stage.

### Additional Information

None.

**Comment by valentine195** [comment]
Hi, I think this is better suited for a dedicated Fantasy Statblocks view, versus using the Combatant window of IT.
