### ISSUE TITLE
🐞 Dice roller not parsed correctly in Black Pudding

### ISSUE THREAD

**Issue by Schamp1** [javalent/fantasy-statblocks#268]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

In the stat block for Black Pudding, here is the ability Corrosive Form :

![image](https://github.com/javalent/fantasy-statblocks/assets/46382119/93f1af98-b9bf-417d-a249-1d5beb22773a)

### Current behaviour

With Dice Roller enabled, there are dice appearing incorrectly before "cumulative -1" and "to -5":

![image](https://github.com/javalent/fantasy-statblocks/assets/46382119/c9426d0f-8e04-4c3a-9a54-097f9cff7734)

### Obsidian Version Check

1.4.5

### Plugin Version

3.9.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
Unfortunately I don't think I can fix this without breaking Ability saves elsewhere.
