### ISSUE TITLE
🧩 Fantasy Statblock - Include Encounter Buttons

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [javalent/fantasy-statblocks#288]
### Scope

Improve Fantasy Statblocks by having a button included in the statblock that can add the monster to Initiative Tracker

### Discovery

Perhaps an option in the settings that allows a user to enable/disable this feature so that people who dont use Initiative Tracker are not impacted. 
But combing them will be a nice QOL improvement. Monster pages would only need to contain the statblock and encounter block can be ignored. 
![image](https://github.com/javalent/fantasy-statblocks/assets/96321415/defda857-ebe3-4e68-aeef-1d35d6792f02)

### Validate

I tested by twirling around 3 times while clapping and touching my nose.

**Comment by valentine195** [comment]
closed with the actions block
