### ISSUE TITLE
🐞 Markdown rendered wikilinks look weird on 3.15.7 

### ISSUE THREAD

**Issue by silentjames** [javalent/fantasy-statblocks#301]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Wikilinks work and are rendered as expected.

### Current behaviour

I use some wikilinks as property value in my statblocks. For example, I link magic abilities to easily see the full description and other conditions.
With new update, markdown rendered links now look like this:
<img width="494" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/12649819/20cf9cf2-f77d-4686-a353-8d256a67bcaa">
"Render as Markdown" toggle is disabled for the first line, and enabled for the second one.
HTML for the first line:
~~~
<div class="statblock-rendered-text-content inline svelte-1lnliuc">
     <a data-href="Хищник" href="Хищник" class="internal-link" target="_blank" rel="noopener">Хищник</a> 
</div>
~~~
HTML for the second line:
~~~
<div class="statblock-markdown svelte-1c3hzq4 el-p" data-tag-name="p">
   <p>
      <a data-href="<STATBLOCK-WIKI-LINK>Одиночка<STATBLOCK-WIKI-LINK>" href="<STATBLOCK-WIKI-LINK>Одиночка<STATBLOCK-WIKI-LINK>" class="internal-link" target="_blank" rel="noopener">&lt;STATBLOCK-WIKI-LINK&gt;Одиночка&lt;STATBLOCK-WIKI-LINK&gt;</a>
   </p>
</div>
~~~
Also, the link itself is wrong in this case:
<img width="886" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/12649819/54cb2ac8-3619-4a6f-897c-f5801c244e1c">

### Reproduction

1.  Create property container;
2. Link monster property as you want, for example "name1:;
3. Add statblock to a note and add name1: [[Other Note Name]];
4. Switch to reading mode -> the link looks fine;
5. Go to statblock settings and toggle "Render as Markdown" on;
6. Return back to the note -> the link looks like `[<STATBLOCK-WIKI-LINK>Other Note Name<STATBLOCK-WIKI-LINK>]` and redirects to empty page.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.4.16 and 1.4.13

### Plugin Version

3.15.7

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
What does the source text look like?

**Comment by silentjames** [comment]
@valentine195 you mean, inside the statblock? 
~~~
nature: [[Хищник]]
demeanor: [[Одиночка]]
concept: [[Солдат]]

**Comment by valentine195** [comment]
Yeah, I have a fix coming soon I think, thanks.

**Comment by valentine195** [comment]
Can you try 3.15.8?

**Comment by silentjames** [comment]
Yes, it works now, thank you!
