### ISSUE TITLE
Unable to enter formulas into Dice Calbacks in the Statblock Layout

### ISSUE THREAD

**Issue by Madmaxneo** [javalent/fantasy-statblocks#314]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I am trying to enter this formula `return [{ text: "1d%!5>=96+" + monster.Stamina}];` into the Dice Callback section of the Property Line in the Statblock Layout. I should be able to add the formula.

### Current behaviour

I am unable to type anything in the Dice Callback or the Callback section as those sections act like they are protected fields and do not allow me to enter anything.

### Reproduction

1. Click on a layout for Statblock. 
2. Then click on add Property line.
3. Click on the pencil symbol to edit the property line
4. Add the name of the monster property you want to add in the "Link Monster Property" box.
5. Scroll down to Dice Callbacks and try to enter anything in that box. It will not allow me to. 
6. I clicked on Render as Markdown but that doesn't help.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

3.16.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
I can't recreate this. Are there any errors in console?

**Comment by Madmaxneo** [comment]
No errors pertaining to Dice Roller or Fantasy Statblocks. The errors I do
have are for missing links in Breadcrumbs and the map icons I added to
Leaflet (the icons do still work though).
Basically the block where you enter the formula for the dice callback will
not let me enter anything, like it's set to not allow entries.

**Comment by Madmaxneo** [comment]
Another thing is that the formulas in the Dice Callbacks I have from before show up at the bottom of the box instead of at the top (where they used to show up at).
![image](https://github.com/javalent/fantasy-statblocks/assets/14065851/9437e3b7-911f-42c6-9ab1-d87686cb12bc)

**Comment by valentine195** [comment]
Unfortunately, I still can't recreate this.
