### ISSUE TITLE
Default statblocks from official documentation (Umbral Dragon) do not work as expected per screenshot

### ISSUE THREAD

**Issue by luigi-lauro** [javalent/fantasy-statblocks#323]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Just created a new vault, installed ONLY fantasy stat blocks & dice roller, didn't change any setting.

Just pasted the example text from: https://plugins.javalent.com/statblock/layouts/integrated/pf2e (Umbra Dragon)

Expected results is rollers which shows the Modifiers and THEN the results, as per screenshot on that webpage. 

<img width="438" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/83593988/da5a5767-a1eb-4311-900d-1f6f1aa94e13">

Instead the modifiers are not shown, just the results (see below).

### Current behaviour

This is the result, with a new vault, minimal plugins, default settings, didn't change anything, just pasted in the correct code fro the website example:

<img width="1792" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/83593988/b7a3ee55-7f01-469a-a526-a011d0b252c6">

<img width="1792" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/83593988/d96feeb5-90c9-46ea-9e8c-46d82db2c318">

### Reproduction

Install obsidian
Create new vault
Install fantasy statblocks & dice roller plugins
Create new note
Paste text block from example documentation (The Filled Codeblock): https://plugins.javalent.com/statblock/layouts/integrated/pf2e 
Results are not as per documentation screenshot, which shows both formulas/modifiers AND results. Only results are shown, pre-rolled.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

Version 1.4.16 (Installer 1.4.16)

### Plugin Version

3.16.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This should no longer be an issue; please re-open if you are seeing it.
