### ISSUE TITLE
📓 Proficiency Bonus parameter ("proficiency") isn't included in the sample statblock

### ISSUE THREAD

**Issue by DrakeDWhite** [javalent/fantasy-statblocks#326]
### What are we changing or adding?

- [X] Repository
- [ ] [Publish Documentation](https://plugins.javalent.com/)

### Location

The main readme for the project. 

### The issue is...

In the example statblock provided at the top, the parameter "proficiency" is not included in the copy and pastable text. From testing it out, I found out that the parameter is simply "proficiency", but this isn't made clear by the documentation.

### Suggestions?

Add a line after "cr" parameter that has "proficiency: <number>" in it. 

### Anything else?

Nope!

**Comment by valentine195** [comment]
Proficiency is a calculated field from CR, the Basic 5e Layout does not use a `proficiency` field
