### ISSUE TITLE
🐞 Statblock rendering issues of spaces and hitpoints

### ISSUE THREAD

**Issue by ElifCase** [javalent/fantasy-statblocks#331]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When rendering a statblock, the 
- size, type, subtype and alignment of a creature should be separated by spaces
- hitpoints of the creatures should be displayed and followed its hitdice in parenthesis
- wikilinks separated by a comma and a space should be rendered rendered as such

### Current behaviour

When rendering a statblock, the
- traits of a creature are separated by commas, not spaces (e.g. "Medium,humanoid,(any race),depends on Party")
- hitdice of the creature are displayed instead of its hitpoints ("Hit Points 4d10+12")
- wikilinks are always followed by an space, even when the next character is a comma or closing parenthesis ("Armor Class 16 (Armor , Shield )")

### Reproduction

1. Launch Obsidian Sandbox via the obsidian Sandbox command
2. Install & enable Fantasy Statblocks
3. Create a new note, paste statblock into it
4. Add local links to the note

```statblock
name: Paladin (Tier 1)
size: Medium
type: humanoid
subtype: (any race)
alignment: depends on Party
ac: 16 ([[Start Here#I’m interested in Obsidian|Armor]], [[Start Here#Official Help Site|Shield]])
hp: 34
hit_dice: 4d10+12
speed: 30ft
stats: [16, 8, 16, 10, 13, 14]
saves:
  - STR: +0
  - WIS: +3
  - CHA: +4
skillsaves:
  - Athletics: +5
senses: Passive Perception 11
languages: Celestial, Common
cr: 2
spells:
  - "The Paladin´s spellcasting ability is Charisma (spell save DC 12, +4 to hit with spell attacks). The paladin can cast the following spells:" 
  - 1/day: bless, command, shield of faith
traits:
  - name: Dueling
    desc: "When the paladin is wielding a melee weapon in one hand and no ther weapons, they gain a +2 bonus to damage rolls with that weapon (included in the longsword attack)"
actions:
  - name: Longsword
    desc: "Mellee Weapon Attack: +5 to hit, reach 5ft., one creature. Hit: 9 (1d8+5) slashing damage"
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [X] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3 and 1.4.16

### Plugin Version

3.16.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by jboehm77** [comment]
This issue is not fully fixed in v4.8.1. hp still do not render if hit_dice is specified.
