### ISSUE TITLE
Centered headers with lines not working in the ITS Theme when fantasy statblocks is also installed

### ISSUE THREAD

**Issue by ActualPlayer** [javalent/fantasy-statblocks#332]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The header is centered with a line in front and a line at the back of the header.
![image](https://github.com/javalent/fantasy-statblocks/assets/54040922/3100f7f5-1b78-40ea-b481-4f381bd9b4c4)

### Current behaviour

The header is not centered and only a line at the back is shown.
![image](https://github.com/javalent/fantasy-statblocks/assets/54040922/eb2ee9fa-525d-4477-8006-f7027a0be530)

### Reproduction

1. Launch a clean vault in obsidian
2. Install the ITS theme and fantasy statblocks plugin
3. Create a new note and add the `hcl` css class
4. Create a header
5. Open the note in reading mode
6. Header is not centered

If you uninstall or disable the fantasy statblocks plugin, the title gets centered in reading mode

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.3 and 1.4.16

### Plugin Version

3.16.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

A conflict in classes used by the theme and the plugin perhaps?

**Comment by valentine195** [comment]
Is this using a theme? If so, you should probably open an issue with the theme, or set up a CSS snippet to fix it. Unfortunately I cannot control themes.
