### ISSUE TITLE
Add layout option to change default columnWidth

### ISSUE THREAD

**Issue by trdischat** [javalent/fantasy-statblocks#341]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The layout should include an option to change the default column width for statblocks.

### Current behaviour

The column width for statblocks defaults to 400.  This can be changed with the `columnWidth` parameter in an individual statblock, but there is no means to change this globally.  A layout option would fix this.

### Reproduction

As noted above, the column width of an individual statblock can be adjusted with the `columnWidth` parameter.  But there is no layout setting to adjust this globally for all statblocks using a particular layout.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.3 and 1.4.13

### Plugin Version

3.17.0

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
This was added in 4.1
