### ISSUE TITLE
Fantasy AGE Stunt Die

### ISSUE THREAD

**Issue by joshua211** [javalent/fantasy-statblocks#346]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

A fantasy age stunt die string (`dice: 1dS`) should be possible to render inside a statblock
 

### Current behaviour

This kind of dice does not seem to be supported. Instead of displaying the dice result, a plain string is rendered.
Using a dice callback makes no difference to this:
![image](https://github.com/javalent/fantasy-statblocks/assets/7515055/e3dd96b4-298d-4d1e-9f01-dcee1d087369)

using other variations, without the dice, also do not work.

![image](https://github.com/javalent/fantasy-statblocks/assets/7515055/b46ddef1-ceec-4177-b38a-ca0a60ccd562)

### Reproduction

Use the stunt die string (1dS) inside a  statblock

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

3.18.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

A simple fix would be to allow parsing dice strings directly from the statblock

_No response_

**Comment by valentine195** [comment]
You are returning the dice string incorrectly. Please follow the example that is shown in the help text above the text area.
