### ISSUE TITLE
🐞 Dice Callback is always shown as property-name's innerText if Dice Roller plugin is not installed or disabled

### ISSUE THREAD

**Issue by silentjames** [javalent/fantasy-statblocks#347]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Even if the property has dice callback added, it should be replaced with simple property value if Dice Roller is not installed or removed.

### Current behaviour

Some of my statblock have lots of properties with dice callbacks inside, and use these properties and callbacks with Dice Roller plugin, obviously. 
But if the plugin is disabled or not installed, dice callback are shown as property name's innerText. Even the callback setting are hidden in "edit block" settings.
<img width="1317" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/12649819/533d1cad-5d81-44bc-8ded-251f08e80850">

### Reproduction

1. Launch Obsidian Sandbox;
2. Install Fantasy Statblock;
3. Install Dice Roller;
4. Create new statblock with a property and valid dice callback in it;
5. Create new note and add the new statblock
6. Go to Community plugins and disable Dice Roller

It also works if user doesn't have Dice Roller installed and imports the pre-made statblock that has dice callbacks.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3 and 1.5.3

### Plugin Version

3.18.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@silentjames Can you send me your layout file?

**Comment by silentjames** [comment]
@valentine195 I think you have already fixed this issue! A month or so ago, here was a Dice Roller related update. And now it works great.

**Comment by valentine195** [comment]
Great, thanks :)
