### ISSUE TITLE
Traits field was not overwrited when specified.

### ISSUE THREAD

**Issue by KSarn21** [javalent/fantasy-statblocks#348]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When specified as follow

```statblock
monster: Ancient Black Dragon
name: Paarthurnax
traits:
  - name: Overwriting Trait
    desc: This trait should overwrited all of the existing traits list, instead of appending to them.
```

The original traits should have been overwrited.

### Current behaviour

When specified as follow

```statblock
monster: Ancient Black Dragon
name: Paarthurnax
traits:
  - name: Overriding Trait
    desc: This trait should overwrited all of the existing traits list, instead of appending to them.
```

The overriding traits appended to the existing list of traits, instead of replacing the original list.

### Reproduction

1. Open Obsidianmd
2. Install the fantasy statblocks plugin
3. Create a new note called "test"
4. Insert the following code

```statblock
creature: Acolyte
actions:
  - name: A
    desc: B
```

5. Action "A" and description "B" will be appended to the  end of the existing actions list instead of overriding it.

### Which Operating Systems are you using?

- [X] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [ ] Windows

### Obsidian Version Check

1.4.16

### Plugin Version

3.18.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by dfaggioli** [comment]
This works for me now. Maybe it has been fixed by https://github.com/javalent/fantasy-statblocks/commit/12df3838d5e755fa2f5aa66cf3188b3dab7a3754 (and can hence be closed)?

**Comment by KSarn21** [comment]
> This works for me now. Maybe it has been fixed by https://github.com/javalent/fantasy-statblocks/commit/12df3838d5e755fa2f5aa66cf3188b3dab7a3754 (and can hence be closed)?

Yes. It also work for me now.
