### ISSUE TITLE
Triple-dot setting button not positioned correctly in Reading View

### ISSUE THREAD

**Issue by sailKiteV** [javalent/fantasy-statblocks#364]
### Check for existing bug reports before submitting. <a href="#user-content-existing-br" id="existing-br">#</a>

- [X] I searched for existing Bug Reports and found no similar reports.

There was a related issue, the solution to which may have accidentally contributed to the behaviour described in this issue: #102

### Expected Behaviour <a href="#user-content-expected-behaviour" id="expected-behaviour">#</a>

The triple-dot setting button will be positioned within the overall statblock container, such as:
![statblock bug 1-1](https://github.com/javalent/fantasy-statblocks/assets/75286796/a5cab062-1e3f-445c-9663-88816f773aa5)

### Current behaviour <a href="#user-content-current-behaviour" id="current-behaviour">#</a>

The triple-dot setting button is positioned relative to the note container or other intervening ancestors with the appropriate `position` value:
![statblock bug 1-2](https://github.com/javalent/fantasy-statblocks/assets/75286796/d7d80dc9-a982-4c55-ac90-ee919b48fe05)

### Reproduction <a href="#user-content-reproduction" id="expected-reproduction">#</a>

1. Launch Obsidian Sandbox via command `Open sandbox vault`.
2. Turn off `Restricted mode` if require in `Settings -> Core plugins`.
3. Install `Fantasy Statblocks` from the plugin store.
4. Enable `Fantasy Statblocks` in `Settings -> Core plugins`.
5. Create a new note via preferred method.
6. Write a `statblock` codeblock into the note, such as
    ```
    ~~~statblock
    creature: Adult Black Dragon
    ~~~
    ```
7. View the note in Reading View.

### Which Operating Systems are you using? <a href="#user-content-which-os" id="which-os">#</a>

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check <a href="#user-content-obsidian-version" id="obsidian-version">#</a>

1.5.8 and 1.5.8

### Plugin Version <a href="#user-content-plugin-version" id="plugin-version">#</a>

4.0.9

### Confirmation <a href="#user-content-confirmation" id="confirmation">#</a>

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution <a href="#user-content-solution" id="solution">#</a>

The following CSS is one possible solution to the problem, and was used to produce the image in the [Expected Behaviour](https://github.com/javalent/fantasy-statblocks/issues/364#expected-behaviour) section:

```css
/* may be worth using .block-language-statblock instead */
.statblock-plugin-parent {
    position: relative;
}
.statblock-plugin-parent .icons:has(> .setting-editor-extra-setting-button) {
    left: var(--size-2-2);
}
```

**Comment by valentine195** [comment]
I think I intentionally put it over there, but I can't recall the exact reason lol

I agree that it looks better closer. I'll try to roll this in with the next update, unless you're willing to PR :)
