### ISSUE TITLE
Bold descriptions for actions reactions and bonus actions in the statblock 

### ISSUE THREAD

**Issue by dgiles474** [javalent/fantasy-statblocks#376]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The entire description should not be bold and Italicized 

### Current behaviour

With the 4.1.1 update, both the title and the description are bolded and in Italics. Just wanted to give you a heads up. Thank you for providing such awesome plug-ins. 

### Reproduction

*

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.11

### Plugin Version

4.1.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by dgiles474** [comment]
This just happens with actions, reactions, and bonus actions.

**Comment by hibeatles** [comment]
same problem
