### ISSUE TITLE
🐞 Markdown text of non-conditional elements transforms into a list

### ISSUE THREAD

**Issue by silentjames** [javalent/fantasy-statblocks#409]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

These elements display a usual `-` as before.

### Current behaviour

In my statblocks I use some properties where "Conditional" parameter is off, and "Fallback" is `-` by default.
In result, it creates a huge `el-ul` > `ul` > `li` construction inside `statblock-markdown` class. Also, almost all themes, including the default one, add dot marker before the (even empty!) list element.
```
<div class="statblock-markdown svelte-1c3hzq4 el-ul" data-tag-name="ul">
   <ul>
      <li>
         ::marker
      </li>
   </ul>
</div>
```

<img width="215" alt="image" src="https://github.com/javalent/fantasy-statblocks/assets/12649819/87652f68-cad7-4dc6-a5a7-b83ccd66cf52">

### Reproduction

1. Create new statblock;
2. Add new property into it;
3. Save changes;
4. Create a note for your new statblock and go to Reading view.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [X] macOS
- [ ] Windows

### Obsidian Version Check

1.5.3 and 1.5.12

### Plugin Version

4.3.3

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

### Possible solution

I hope it's possible to switch it back to the `statblock-markdown` > `p`, for example.

**Comment by valentine195** [comment]
This is a side effect of doing markdown rendering by default. Guess I need to escape this case. Thanks.
