### ISSUE TITLE
Adding to traits field not working as expected

### ISSUE THREAD

**Issue by dralois** [javalent/fantasy-statblocks#421]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The added trait is appended once at the end of the list of existing traits.

### Current behaviour

The trait is appended three times, once before the list of existing traits and twice after.

![image](https://github.com/javalent/fantasy-statblocks/assets/4374949/480083b9-d0f2-4c30-b229-93cbc28af226)

### Reproduction

1) Create a stat block in any file
2) Append any new trait to the traits field

e.g.:
```statblock
monster: Unicorn
traits+:
  - name: Test
    desc: Test
```

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.12

### Plugin Version

4.4.2

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by AYelland** [comment]
I am also finding this issue on the MacOS version

**Comment by MalGanis247** [comment]
The exact same thing happens on adding to actions.
One entry is added above the existing actions and two below.

(Obsidian v1.6.7, Fantasy Statblock v4.6.0, Windows)
