### ISSUE TITLE
🐞 PF2e Webp - Images have stopped rendering

### ISSUE THREAD

**Issue by ObsidianTTRPGProject** [javalent/fantasy-statblocks#455]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Images should display in the statblock. 

### Current behaviour

Images are not rendering. They show as: 
![image](https://github.com/user-attachments/assets/3f62b46a-d7fe-4fbf-8673-a818fd27bdbc)

### Reproduction

They displayed prior to me updating all my plugins. 
Replicated with another  user. 
Replicated with a brand new vault. 
Can display the image outside of the statblock with the same syntax. 

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

v1.7.1

### Plugin Version

4.7.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by ObsidianTTRPGProject** [comment]
ok we made it work. 

Used to work like this: [[modules/pf2e-tokens-bestiaries/portraits/bestial/mammalian/cave-bear.webp]]

Now it only works like this: modules/pf2e-tokens-bestiaries/portraits/bestial/mammalian/cave-bear.webp

**Comment by Madmaxneo** [comment]
Is that the solution? Do I need to now go in and adjust 450+ statblocks to get the images to show up?

**Comment by ObsidianTTRPGProject** [comment]
Confirming issue has been solved with [Fantasy Statblocks Release - v4.7.5](https://github.com/javalent/fantasy-statblocks/releases/tag/4.7.5)
