### ISSUE TITLE
🐞 Appending (via "section+") to section not work properly

### ISSUE THREAD

**Issue by vkochurov** [javalent/fantasy-statblocks#456]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

The **"actions:"** section should show only one entrance of property added.

### Current behaviour

When i try to **append** to existing monster section, actions as example, using "actions+" syntax, i receive several copy of new property in _statblock_. Other section - "traits:" give similar results.
#### Example yaml
```yaml
creature: Lesser Krumsh
name: Krumsh
actions+:
  - name: TEST
    desc: TEST
```
### Screenshot of result
![image](https://github.com/user-attachments/assets/c87a71c2-2604-4237-87cc-3c8d35ab17bc)

### Reproduction

1. Have a base monster in Bestiary formed using front-matter yaml method.
2. Create new statblock for monster with extended properties.
3. Add some property with appending method
4. Look at new monster in edit or in view mode - you will see several copy of property added

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.6.7

### Plugin Version

4.7.1

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by dralois** [comment]
To tag onto this, this issue likely is related to or the same as [the one I opened a while ago](https://github.com/javalent/fantasy-statblocks/issues/421).

**Comment by vkochurov** [comment]
Gone in 4.7.8 
![image](https://github.com/user-attachments/assets/25961be0-337b-47aa-b05f-b2768e1ce538)
