### ISSUE TITLE
Feature Request: 5e character sheet layout

### ISSUE THREAD

**Issue by fenjalien** [javalent/fantasy-statblocks#47]
It would be great to be able to create player characters, in a similar way roll20 does, using this tool. 

It should be possible to recreate it using the current custom layout minus all the fancy graphics but you can't nest inline groups which means everything is placed in columns.

**Comment by sigrunixia** [comment]
@fenjalien 

A true character sheet like the ones on Roll20, or even a paper based one, would be quite resource heavy. That being said, check this out first and let me know what you think please.

https://github.com/valentine195/fantasy-statblocks/discussions/169

**Comment by sigrunixia** [comment]
For now, designing this ourselves is outside the scope and and time of myself and Javalent. As we are giving users the tools to accomplish this themselves, I am closing this thread.
