### ISSUE TITLE
Removing Features from Statblock

### ISSUE THREAD

**Issue by Oudwins** [javalent/fantasy-statblocks#51]
Hey!

Thank you for this. The plugin is amazing. 

I am wondering if it is possible to not replace but rather remove features from the statblock without using a custom layout. Sometimes it works and sometimes it doesnt. For example:

If I override spells like so
```statblock
monster: spellcaster
spells:
```

The spells are removed (the entire section).

But if I want to remove a specific trait it doesnt work.

This leaves all traits intact. 
```statblock
monster: ...
traits:
```

And this removes the description but the trait stays.
```statblock
monster: ...
traits:
- name: trait to remove
  desc: 
```

This would be very useful since premade statblocks are so bloated they take up my entire note (specially monsters of 6+ CR they usually have a bunch of not very relevant traits)....

**Comment by sigrunixia** [comment]
@Oudwins 
As you go about poking at Statblocks later for the other topic, a release for #156 also has the effect that your request should now consistently work. Could you check at some point and get back and confirm?
